#!/bin/bash
# shellcheck disable=SC2034

# Backgroud Image
#IMAGE="$HOME/.config/sway/wallpaper/lockscreen.png"

# Colors
#bg='1B1F28'    bgl='2F333C'      fg='EEEEEE'
#red='E06B74'   green='98C379'    yellow='E5C07A'
#blue='62AEEF'  magenta='C77800'  cyan='55B6C2'

bg="1B1F28ff"    
bge6="1B1F28E6"    
bgl="2F333Cff"      
fg="EEEEEEff"
red="E06B74ff"   
green="98C379ff"    
yellow="E5C07Aff"
blue="62AEEFff"  
magenta="C77800ff"  
cyan="55B6C2ff"
alpha="00000000"

IMAGE=""
if [ "$1" != "" ]
then
    IMAGE="-i $1"
fi

# CMD
swaylock -f ${IMAGE} \
    \
    --ignore-empty-password \
    --show-failed-attempts \
    --hide-keyboard-layout \
    --indicator-caps-lock \
    \
    --indicator-thickness 15 \
    --indicator-radius 120 \
    \
    --color ${bge6} \
    \
    --key-hl-color ${green} \
    --caps-lock-key-hl-color ${blue} \
    --bs-hl-color ${red} \
    --caps-lock-bs-hl-color ${red} \
    \
    --indicator-radius 120 \
    --indicator-thickness 10 \
    \
    --inside-color ${alpha} \
    --inside-clear-color ${alpha} \
    --inside-caps-lock-color ${alpha} \
    \
    --ring-color ${cyan} \
    --ring-clear-color ${cyan} \
    --ring-caps-lock-color ${alpha} \
    \
    --line-color ${alpha} \
    --line-clear-color ${bgl} \
    --line-caps-lock-color ${alpha} \
    \
    --inside-ver-color ${blue} \
    --line-ver-color ${bgl} \
    --ring-ver-color ${blue} \
    \
    --inside-wrong-color ${red} \
    --line-wrong-color ${bgl} \
    --ring-wrong-color ${red} \
    \
    --separator-color ${bgl} \
    \
    --text-color ${fg} \
    --text-clear-color ${fg} \
    --text-caps-lock-color ${fg} \
    --text-ver-color ${fg} \
    --text-wrong-color ${fg} \

