#!/bin/bash

# Backgroud Image
#IMAGE="$HOME/.config/sway/wallpaper/lockscreen.png"

# Colors
bg='1B1F28'    bgl='2F333C'      fg='EEEEEE'
red='E06B74'   green='98C379'    yellow='E5C07A'
blue='62AEEF'  magenta='C77800'  cyan='55B6C2'
alpha='00000000'

# CMD

swaylock -f \
    \
    '#General' \
    --ignore-empty-password \
    --show-failed-attempts \
    --hide-keyboard-layout \
    --indicator-caps-lock \
    \
    '# Appearance' \
    --color ${bg}E6 \
    '#--font 'JetBrainsMono Nerd Font' --font-size 18' \
    \
    '# Backspace key' \
    --key-hl-color ${green} \
    --caps-lock-key-hl-color ${blue} \
    --bs-hl-color ${red} \
    --caps-lock-bs-hl-color ${red} \
    \
    '# Indicator' \
    --indicator-radius 120 \
    --indicator-thickness 10 \
    \
    '# Inside colors' \
    --inside-color ${alpha} \
    --inside-clear-color ${alpha} \
    --inside-caps-lock-color ${alpha} \
    \
    --ring-color ${cyan} \
    --ring-clear-color ${cyan} \
    --ring-caps-lock-color ${alpha} \
    \
    --line-color ${alpha} \
    --line-clear-color ${bgl} \
    --line-caps-lock-color ${alpha} \
    \
    --inside-ver-color ${blue} \
    --line-ver-color ${bgl} \
    --ring-ver-color ${blue} \
    \
    --inside-wrong-color ${red} \
    --line-wrong-color ${bgl} \
    --ring-wrong-color ${red} \
    \
    --separator-color ${bgl} \
    \
    --text-color ${fg} \
    --text-clear-color ${fg} \
    --text-caps-lock-color ${fg} \
    --text-ver-color ${fg} \
    --text-wrong-color ${fg} \

