#!/bin/bash

# alacritty -o font.size=12
# kitty -o font_size=12
# foot -o main.font=monospace:size=8
# xterm
# xfce4-terminal
# shellcheck disable=SC2068


alacritty_term()
{
  if [[ "$(which alacritty 2>/dev/null)" != "" ]]; then
    alacritty -o font.size=10.0 $@
  fi
}
foot_term()
{
  if [[ "$(which foot 2>/dev/null)" != "" ]]; then
    foot -o "main.font=Hack Nerd Font:size=10.0"  $@
  fi
}
kitty_term()
{
  if [[ "$(which kitty 2>/dev/null)" != "" ]]; then
    kitty -o font_size=10  $@
  fi
}
xterm_term()
{
  if [[ "$(which xterm 2>/dev/null)" != "" ]]; then
    xterm -bg black -fg white  $@
  fi
}


case "$1" in
  alacritty) shift; alacritty_term $@ ;;
  foot) shift; foot_term $@ ;;
  kitty) shift; kitty_term $@ ;;
  xterm) shift; xterm_term $@ ;;
  *) alacritty_term $@ ;;
esac

