#!/bin/bash
##############################################################################
# fancy-i3lock
# -----------
# Based on the awesome sauce of https://github.com/meskarune/i3lock-fancy
# This just uses imagemagick.
#
# Based on a similar script from Jess Frazelle (@jezzfraz) but simpler.
#
# Requires: i3lock, scrot, imagemagick
#
##############################################################################
set -e

# subshell this shiz
(
IMAGE=/tmp/i3lock.png

# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
# BLURTYPE="0x5" # 7.52s
# BLURTYPE="0x2" # 4.39s
BLURTYPE="5x3" # 3.80s
# BLURTYPE="2x8" # 2.90s
# BLURTYPE="2x3" # 2.92s

scrot $IMAGE

# original convertion
#convert $IMAGE -brightness-contrast -30x10 -level 0%,100%,0.6 -blur $BLURTYPE -gravity center - | composite -gravity center $HOME/.local/share/icons/lock.png - $IMAGE

# just blur the screenshot
#convert $IMAGE  -level 0%,100%,0.8 -blur $BLURTYPE -gravity center $IMAGE

# add text and lock image to screenshot
convert $IMAGE -brightness-contrast 10x10 -level 0%,100%,0.8 -blur $BLURTYPE -font Roboto-Regular -pointsize 26 -fill white -gravity center -annotate +0+160 "Type Password to Unlock" "$HOME"/.local/share/icons/lock.png -gravity center -composite $IMAGE

i3lock -i $IMAGE

rm -f $IMAGE
rm -f ${IMAGE%.*}*.png
)

