#!/usr/bin/env sh

load="$(cut -d' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

echo "$load"

echo "$load"

awk -v cpus=$cpus -v cpuload=$load '
    BEGIN {
        if (cpus <= cpuload) {
            print "#ff0000";
            exit 33;
        }
    }
'

