#!/bin/bash
# Requires: xorg-xprop

ACTIVE_WINDOW=$(xprop -id "$(xprop -root _NET_ACTIVE_WINDOW | cut -d' ' -f5)" WM_NAME | cut -d'"' -f2)

if [[ "$ACTIVE_WINDOW" != "" ]]; then
  echo "$ACTIVE_WINDOW     "
  echo "$ACTIVE_WINDOW"
  #echo ""
fi

